namespace TeraSyncV2Shared.Metrics;

public class MetricsAPI
{
    public const string CounterInitializedConnections = "tera_initialized_connections";
    public const string GaugeConnections = "tera_connections";
    public const string GaugeAuthorizedConnections = "tera_authorized_connections";
    public const string GaugeAvailableWorkerThreads = "tera_available_threadpool";
    public const string GaugeAvailableIOWorkerThreads = "tera_available_threadpool_io";
    public const string GaugeUsersRegistered = "tera_users_registered";
    public const string CounterUsersRegisteredDeleted = "tera_users_registered_deleted";
    public const string GaugePairs = "tera_pairs";
    public const string GaugePairsPaused = "tera_pairs_paused";
    public const string GaugeFilesTotal = "tera_files";
    public const string GaugeFilesTotalColdStorage = "tera_files_cold";
    public const string GaugeFilesTotalSize = "tera_files_size";
    public const string GaugeFilesTotalSizeColdStorage = "tera_files_size_cold";
    public const string GaugeFilesDownloadingFromCache = "tera_files_downloading_from_cache";
    public const string GaugeFilesTasksWaitingForDownloadFromCache = "tera_files_waiting_for_dl";
    public const string CounterUserPushData = "tera_user_push";
    public const string CounterUserPushDataTo = "tera_user_push_to";
    public const string CounterAuthenticationRequests = "tera_auth_requests";
    public const string CounterAuthenticationCacheHits = "tera_auth_requests_cachehit";
    public const string CounterAuthenticationFailures = "tera_auth_requests_fail";
    public const string CounterAuthenticationSuccesses = "tera_auth_requests_success";
    public const string GaugeAuthenticationCacheEntries = "tera_auth_cache";
    public const string GaugeGroups = "tera_groups";
    public const string GaugeGroupPairs = "tera_groups_pairs";
    public const string GaugeFilesUniquePastHour = "tera_files_unique_past_hour";
    public const string GaugeFilesUniquePastHourSize = "tera_files_unique_past_hour_size";
    public const string GaugeFilesUniquePastDay = "tera_files_unique_past_day";
    public const string GaugeFilesUniquePastDaySize = "tera_files_unique_past_day_size";
    public const string GaugeCurrentDownloads = "tera_current_downloads";
    public const string GaugeQueueFree = "tera_download_queue_free";
    public const string GaugeQueueActive = "tera_download_queue_active";
    public const string GaugeQueueInactive = "tera_download_queue_inactive";
    public const string GaugeDownloadQueue = "tera_download_queue";
    public const string GaugeDownloadQueueCancelled = "tera_download_queue_cancelled";
    public const string GaugeDownloadPriorityQueue = "tera_download_priority_queue";
    public const string GaugeDownloadPriorityQueueCancelled = "tera_download_priority_queue_cancelled";
    public const string CounterFileRequests = "tera_files_requests";
    public const string CounterFileRequestSize = "tera_files_request_size";
    public const string CounterUserPairCacheHit = "tera_pairscache_hit";
    public const string CounterUserPairCacheMiss = "tera_pairscache_miss";
    public const string GaugeUserPairCacheUsers = "tera_pairscache_users";
    public const string GaugeUserPairCacheEntries = "tera_pairscache_entries";
    public const string CounterUserPairCacheNewEntries = "tera_pairscache_new_entries";
    public const string CounterUserPairCacheUpdatedEntries = "tera_pairscache_updated_entries";
    public const string GaugeGposeLobbies = "tera_gpose_lobbies";
    public const string GaugeGposeLobbyUsers = "tera_gpose_lobby_users";
    public const string GaugeHubConcurrency = "tera_free_concurrent_hub_calls";
    public const string GaugeHubQueuedConcurrency = "tera_free_concurrent_queued_hub_calls";
}